### ISSUE TITLE
Does not compile on OpenJDK 11, default in Ubuntu 19.04 

### ISSUE THREAD

**Issue by berkes** [OpenPlaceReviews/opendb#28]
Installing the alternative java-8 fixes this.

`sudo update-alternatives --config java`

Maybe this can be included in the build, though. As if fails on a missing library.

`java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`

Solutuitions documented here: https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by vshcherb** [comment]
Yes it is a known issue. We will need to address it.

**Comment by vshcherb** [comment]
Fixed
